# Generated by Django 3.2.1 on 2024-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessCartegory', models.TextField()),
                ('businessBio', models.TextField()),
                ('businessObjective', models.TextField()),
                ('businessGoal', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
